underlay:
    local:
        asn: 60023
    neighbors:
      - interface: "{{ topo[inventory_hostname].port1.name }}"
        name: "{{ topo[inventory_hostname].port1.peer }}"
        asn: 60013
        peer_ip: "{{ p2p.link13.1}}"
        local_ip: "{{ p2p.link13.2}}"
      - interface: "{{ topo[inventory_hostname].port2.name }}"
        name: "{{ topo[inventory_hostname].port2.peer }}"
        asn: 60014
        peer_ip: "{{ p2p.link15.1}}"
        local_ip: "{{ p2p.link15.2}}"
