
underlay:
    local:
        asn: 65023
    neighbors:
      - interface: xe-0/0/3
        name: leaf-04
        asn: 65034
        peer_ip: 172.16.0.27
        local_ip: 172.16.0.26
      - interface: xe-0/0/1
        name: fabric-02
        asn: 65012
        peer_ip: 172.16.0.19
        local_ip: 172.16.0.18
      - interface: xe-0/0/2
        name: leaf-03
        asn: 65033
        peer_ip: 172.16.0.25
        local_ip: 172.16.0.24
      - interface: xe-0/0/0
        name: fabric-01
        asn: 65011
        peer_ip: 172.16.0.17
        local_ip: 172.16.0.16
