
underlay:
    local:
        asn: 60022
    neighbors:
      - interface: "{{ topo[inventory_hostname].port1.name }}"
        name: "{{ topo[inventory_hostname].port1.peer }}"
        asn: 60011
        peer_ip: "{{ p2p.link10.1}}"
        local_ip: "{{ p2p.link10.2}}"
      - interface: "{{ topo[inventory_hostname].port2.name }}"
        name: "{{ topo[inventory_hostname].port2.peer }}"
        asn: 60012
        peer_ip: "{{ p2p.link12.1}}"
        local_ip: "{{ p2p.link12.2}}"
