
underlay:
    leaf: true
    local:
        asn: 60012
    neighbors:
      - interface: et-0/0/51
        name: spine-02
        asn: 60014
        peer_ip: 172.16.0.6
        local_ip: 172.16.0.7
      - interface: et-0/0/50
        name: spine-01
        asn: 60012
        peer_ip: 172.16.0.2
        local_ip: 172.16.0.3
