underlay:
    local:
        asn: 60012
    community: target:12345:111
    neighbors:

## Fabric
      - interface: "{{ topo[inventory_hostname].port3.name }}"
        name: "{{ topo[inventory_hostname].port3.peer }}"
        asn: 60001
        peer_ip: "{{ p2p.link3.2}}"
        local_ip: "{{ p2p.link3.1}}"
      - interface: "{{ topo[inventory_hostname].port4.name }}"
        name: "{{ topo[inventory_hostname].port4.peer }}"
        asn: 60002
        peer_ip: "{{ p2p.link4.2}}"
        local_ip: "{{ p2p.link4.1}}"

## Leaf
      - interface: "{{ topo[inventory_hostname].port1.name }}"
        name: "{{ topo[inventory_hostname].port1.peer }}"
        asn: 60021
        peer_ip: "{{ p2p.link11.2}}"
        local_ip: "{{ p2p.link11.1}}"
      - interface: "{{ topo[inventory_hostname].port2.name }}"
        name: "{{ topo[inventory_hostname].port2.peer }}"
        asn: 60022
        peer_ip: "{{ p2p.link12.2}}"
        local_ip: "{{ p2p.link12.1}}"
