
access:
    interfaces:
        -   name: "{{ topo[inventory_hostname].port3.name }}"
            description: "{{ topo[inventory_hostname].port3.peer }}"
            mode: normalize
            vni_vlans_mapping:
              9105:  10
              9106:  11
        -   name: "{{ topo[inventory_hostname].port4.name }}"
            description: "{{ topo[inventory_hostname].port4.peer }}"
            mode: normalize
            vni_vlans_mapping:
              9105:  10
              9106:  11
              9107:  12
              9108:  13
