underlay:
    local:
        asn: 60011
    community: target:12345:111
    neighbors:

## Fabric
      - interface: "{{ topo[inventory_hostname].port3.name }}"
        name: "{{ topo[inventory_hostname].port3.peer }}"
        asn: 60001
        peer_ip: "{{ p2p.link1.2}}"
        local_ip: "{{ p2p.link1.1}}"
      - interface: "{{ topo[inventory_hostname].port4.name }}"
        name: "{{ topo[inventory_hostname].port4.peer }}"
        asn: 60002
        peer_ip: "{{ p2p.link2.2}}"
        local_ip: "{{ p2p.link2.1}}"

## Leaf
      - interface: "{{ topo[inventory_hostname].port1.name }}"
        name: "{{ topo[inventory_hostname].port1.peer }}"
        asn: 60021
        peer_ip: "{{ p2p.link9.2}}"
        local_ip: "{{ p2p.link9.1}}"
      - interface: "{{ topo[inventory_hostname].port2.name }}"
        name: "{{ topo[inventory_hostname].port2.peer }}"
        asn: 60022
        peer_ip: "{{ p2p.link10.2}}"
        local_ip: "{{ p2p.link10.1}}"
